name: Basic Job
on:
    push: 
        branches: ['main','feature/basic']
jobs:
  basic_job: 
    name: Basic Job
    runs-on: ubuntu-latest
    steps:
      - name: Running Echo 
        run: echo "Hello World"

