name: Generate Ascii
on:
    workflow_dispatch
jobs:
    generate_dragon:
        runs-on:
            [ubuntu-latest]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Install Cowsay
              run: sudo apt-get update && sudo apt-get install cowsay -y
            - name: Execute Cowsay
              run: grep -i "dragon" dragon.txt
            - name: Display Artwork
              run: cat dragon.txt
            - name: List Repository Files
              run: ls -ltra