name: variable-example
on: 
    push: 

env: 
    CMD: push

jobs:
    Multiple-Variable:
      runs-on: ubuntu-latest
      env: # Job level env variable
        DOCKER_CMD: docker
        #DEPLOY_IMAGE: aditule/test:adi
      steps:
        - name: Docker Build
          env: # Step level env variable
            DOCKER_CMD: docker
            IMAGE: alpine
          run: $DOCKER_CMD pull ${{ env.IMAGE }}
        - name: Docker Tag
          run: docker tag alpine:latest ${{ vars.DEPLOY_IMAGE }}
        - name: Docker login
          run: docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_PASSWORD }}
        - name: Docker ${{ env.CMD }}
          run: docker $CMD ${{ vars.DEPLOY_IMAGE }}

