name: variable-example
on: 
    workflow_dispatch: 

jobs:
    Multiple-Variable:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Build
          run: docker pull alpine
        - name: Docker image list
          run: docker images
        - run: docker image ls | grep alpine
