name: variable-example
on: 
    push: 

jobs:
    Multiple-Variable:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Build
          run: docker pull alpine
        - name: Docker Tag
          run: docker tag alpine:latest aditule/test:adi
        - name: Docker login
          run: docker login --username=aditule --password=Cooldudes786*
        - name: Docker push
          run: docker push aditule/test:adi

